[extension]
id = "one-dark-soft"
name = "One Dark Soft"
description = "One Dark Soft theme for Zed Editor"
version = "0.1.0"
authors = ["Suyadi <suyadi.1992@gmail.com>"]
repository = "https://github.com/esyede/zed-one-dark-soft"

[extension.themes]
themes = ["themes/one-dark-soft.json"]
keywords = ["theme", "dark", "one-dark", "soft", "atom"]
